name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  download_docs:
    runs-on: ubuntu-latest
    steps:      
      - name: Download docs
        uses: workflow/nix-shell-action@v1
        with:
          script: |
            curl -o docs.zip https://storage.googleapis.com/docscloudstorage/2019.4/UnityDocumentation.zip
            unzip -d UnityDocumentation docs.zip
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload Converter
      uses: actions/upload-artifact@v2.2.0
      with:
        name: converter
        path: OpenUnityDocs.Converter/bin/Release/netcoreapp3.1/
        if-no-files-found: error
